// <auto-generated />

using System.Diagnostics.CodeAnalysis;
using GrisAPI.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrisAPI.Migrations
{
    [ExcludeFromCodeCoverage]
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardDeck", b =>
                {
                    b.Property<int>("CardsId")
                        .HasColumnType("integer");

                    b.Property<int>("DecksId")
                        .HasColumnType("integer");

                    b.HasKey("CardsId", "DecksId");

                    b.HasIndex("DecksId");

                    b.ToTable("CardDeck");
                });

            modelBuilder.Entity("CardExtraDeck", b =>
                {
                    b.Property<int>("CardsId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraDecksId")
                        .HasColumnType("integer");

                    b.HasKey("CardsId", "ExtraDecksId");

                    b.HasIndex("ExtraDecksId");

                    b.ToTable("CardExtraDeck");
                });

            modelBuilder.Entity("CreatureDeck", b =>
                {
                    b.Property<int>("CreaturesId")
                        .HasColumnType("integer");

                    b.Property<int>("DecksId")
                        .HasColumnType("integer");

                    b.HasKey("CreaturesId", "DecksId");

                    b.HasIndex("DecksId");

                    b.ToTable("CreatureDeck");
                });

            modelBuilder.Entity("CreatureUser", b =>
                {
                    b.Property<int>("CreaturesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer");

                    b.HasKey("CreaturesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("CreatureUser");
                });

            modelBuilder.Entity("DeckJoker", b =>
                {
                    b.Property<int>("DecksId")
                        .HasColumnType("integer");

                    b.Property<int>("JokersId")
                        .HasColumnType("integer");

                    b.HasKey("DecksId", "JokersId");

                    b.HasIndex("JokersId");

                    b.ToTable("DeckJoker");
                });

            modelBuilder.Entity("ExtraDeckJoker", b =>
                {
                    b.Property<int>("ExtraDecksId")
                        .HasColumnType("integer");

                    b.Property<int>("JokersId")
                        .HasColumnType("integer");

                    b.HasKey("ExtraDecksId", "JokersId");

                    b.HasIndex("JokersId");

                    b.ToTable("ExtraDeckJoker");
                });

            modelBuilder.Entity("GrisAPI.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Manifestation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Symbol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("GrisAPI.Models.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExtraDeckId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExtraDeckId")
                        .IsUnique();

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("GrisAPI.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NumberOfCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("GrisAPI.Models.ExtraDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ExtraDecks");
                });

            modelBuilder.Entity("GrisAPI.Models.Joker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Jokers");
                });

            modelBuilder.Entity("GrisAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CardDeck", b =>
                {
                    b.HasOne("GrisAPI.Models.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrisAPI.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("DecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardExtraDeck", b =>
                {
                    b.HasOne("GrisAPI.Models.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrisAPI.Models.ExtraDeck", null)
                        .WithMany()
                        .HasForeignKey("ExtraDecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatureDeck", b =>
                {
                    b.HasOne("GrisAPI.Models.Creature", null)
                        .WithMany()
                        .HasForeignKey("CreaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrisAPI.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("DecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatureUser", b =>
                {
                    b.HasOne("GrisAPI.Models.Creature", null)
                        .WithMany()
                        .HasForeignKey("CreaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrisAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeckJoker", b =>
                {
                    b.HasOne("GrisAPI.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("DecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrisAPI.Models.Joker", null)
                        .WithMany()
                        .HasForeignKey("JokersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtraDeckJoker", b =>
                {
                    b.HasOne("GrisAPI.Models.ExtraDeck", null)
                        .WithMany()
                        .HasForeignKey("ExtraDecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrisAPI.Models.Joker", null)
                        .WithMany()
                        .HasForeignKey("JokersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrisAPI.Models.Creature", b =>
                {
                    b.HasOne("GrisAPI.Models.ExtraDeck", "ExtraDeck")
                        .WithOne("Creature")
                        .HasForeignKey("GrisAPI.Models.Creature", "ExtraDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraDeck");
                });

            modelBuilder.Entity("GrisAPI.Models.ExtraDeck", b =>
                {
                    b.Navigation("Creature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
